language: python
python:
    - 2.6
    - 2.7
    - 3.2

install:
    - pip install docutils
    - python setup.py install

branches:
    only:
        - master

script:
    - cd tests
    - nosetests
