# -*- coding: utf-8 -*-
#: settings for liquidluck

#: site information
#: all variables can be accessed in template with ``site`` namespace.
#: for instance: {{site.name}}
site:
    name: Felix Felicis # your module name
    url: "http://lab.lepture.com/liquidluck/"

#: this config defined information of your site
#: 1. where the resources  2. how should the site be generated
config:
    source: .
    output: .
    static: ./static
    permalink: "{{folder}}/{{filename}}.html"
    relative_url: true


author:
    default: lepture
    vars:
        # key: value

#: active readers
reader:
    active:
        - liquidluck.readers.markdown.MarkdownReader
        - liquidluck.readers.restructuredtext.RestructuredTextReader
    vars:
        post_class: chiang.ChiangPost

#: active writers
writer:
    active:
        - liquidluck.writers.core.PostWriter
        - liquidluck.writers.core.StaticWriter

#: theme variables
theme:
    name: chiang
    vars:
        mainnav:
        sidenav:
